### ISSUE TITLE
Autocompletion opens a new horizontal split

### ISSUE THREAD

**Issue by joeybaker** [wokalski/autocomplete-flow#5]
When using `tab` to autocomplete an autosuggestion from this plugin, a new split opens with a buffer containing the flow type for the autocompleted phrase. It's kinda weird and likely a bug, but a the very least it would be nice to be able to turn off.

![screen shot 2017-08-04 at 08 57 49](https://user-images.githubusercontent.com/36662/28976554-3216cd4e-78f3-11e7-9740-0530cdd96604.png)

**Comment by joeybaker** [comment]
My bad, I just needed to set `set completeopt-=preview`. Sorry for the spam.

**Comment by wokalski** [comment]
Np. I don't use this plugin anymore (I don't use Js anymore) but the last time I saw it, it was a bit broken so sorry for any inconvenience.

**Comment by joeybaker** [comment]
It seems to be working okay so far, do you remember what was broken?

**Comment by wokalski** [comment]
Last time I checked it spawned waaay too many `flow` instances. It should probably use the newer server APIs.

**Comment by joeybaker** [comment]
Got it. Good to know, thanks!
